# Generated by Django 5.1.15 on 2026-06-04 08:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50)),
                ('capacity', models.IntegerField(default=20)),
                ('current_occupancy', models.IntegerField(default=0)),
                ('max_weight', models.DecimalField(blank=True, decimal_places=2, help_text='kg', max_digits=8, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('audit_type', models.CharField(choices=[('FULL', 'Full Audit'), ('SPOT', 'Spot Check'), ('CYCLE', 'Cycle Count')], max_length=50)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('DISCREPANCY', 'Discrepancy Found')], default='IN_PROGRESS', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50)),
                ('barcode', models.CharField(blank=True, max_length=255)),
                ('capacity', models.IntegerField(default=5)),
                ('current_occupancy', models.IntegerField(default=0)),
                ('is_full', models.BooleanField(default=False)),
                ('is_locked', models.BooleanField(default=False)),
                ('shelf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='warehouse.shelf')),
            ],
            options={
                'unique_together': {('shelf', 'code')},
            },
        ),
        migrations.CreateModel(
            name='StoredItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('item_name', models.CharField(max_length=255)),
                ('barcode', models.CharField(blank=True, max_length=255)),
                ('stored_at', models.DateTimeField(auto_now_add=True)),
                ('retrieved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('box', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stored_items', to='warehouse.box')),
                ('retrieved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retrieved_items', to=settings.AUTH_USER_MODEL)),
                ('shelf', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stored_items', to='warehouse.shelf')),
                ('storage_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stored_items', to='customers.storagerequest')),
                ('stored_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stored_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-stored_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryAuditItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('expected_location', models.CharField(max_length=255)),
                ('actual_location', models.CharField(max_length=255)),
                ('is_found', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='warehouse.inventoryaudit')),
                ('stored_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.storeditem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('address', models.TextField()),
                ('capacity', models.IntegerField(default=1000, help_text='Maximum items')),
                ('current_occupancy', models.IntegerField(default=0)),
                ('has_refrigeration', models.BooleanField(default=False)),
                ('has_fragile_section', models.BooleanField(default=False)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('operating_hours', models.JSONField(blank=True, default=dict)),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_warehouses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='storeditem',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stored_items', to='warehouse.warehouse'),
        ),
        migrations.AddField(
            model_name='inventoryaudit',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='warehouse.warehouse'),
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('capacity', models.IntegerField(default=200)),
                ('current_occupancy', models.IntegerField(default=0)),
                ('zone_type', models.CharField(choices=[('GENERAL', 'General'), ('FRAGILE', 'Fragile'), ('REFRIGERATED', 'Refrigerated'), ('HIGH_VALUE', 'High Value'), ('OVERSIZE', 'Oversize')], default='GENERAL', max_length=50)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='warehouse.warehouse')),
            ],
            options={
                'unique_together': {('warehouse', 'code')},
            },
        ),
        migrations.AddField(
            model_name='storeditem',
            name='zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stored_items', to='warehouse.zone'),
        ),
        migrations.AddField(
            model_name='shelf',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelves', to='warehouse.zone'),
        ),
        migrations.AddIndex(
            model_name='storeditem',
            index=models.Index(fields=['warehouse', 'zone', 'shelf', 'box'], name='warehouse_s_warehou_cbb752_idx'),
        ),
        migrations.AddIndex(
            model_name='storeditem',
            index=models.Index(fields=['storage_request'], name='warehouse_s_storage_e20e39_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='shelf',
            unique_together={('zone', 'code')},
        ),
    ]
